---
version: "3.8"
services:
  movies:
    image: pavan4040/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: pavan4040/paytrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: pavan4040/paydth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: pavan4040/payrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
